import { BACKEND_PERMISSIONS, DESIGN_PERMISSIONS, PROJECT_PERMISSIONS, USER_PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: [
    // User
    ...Object.values(USER_PERMISSIONS),
    
    // Projects
    ...Object.values(PROJECT_PERMISSIONS),

    // UI/UX
    ...Object.values(DESIGN_PERMISSIONS),

    // Backend
    ...Object.values(BACKEND_PERMISSIONS),
  ],

  ADMIN: [
    USER_PERMISSIONS.GET_OWN_DATA,
    USER_PERMISSIONS.GET_OTHER_DATA,
    USER_PERMISSIONS.UPDATE_OTHER_DATA,

    PROJECT_PERMISSIONS.GET_ALL,
    PROJECT_PERMISSIONS.UPDATE_ANY,
    PROJECT_PERMISSIONS.DELETE_ANY,

    DESIGN_PERMISSIONS.VIEW_UIUX,
    DESIGN_PERMISSIONS.UPDATE_UIUX,

    BACKEND_PERMISSIONS.VIEW_BACKEND,
    BACKEND_PERMISSIONS.UPDATE_BACKEND,
  ],

  USER: [
    USER_PERMISSIONS.GET_OWN_DATA,
    USER_PERMISSIONS.UPDATE_OWN_DATA,
    USER_PERMISSIONS.DELETE_OWN,

    PROJECT_PERMISSIONS.CREATE,
    PROJECT_PERMISSIONS.GET_OWN,
    PROJECT_PERMISSIONS.UPDATE_OWN,
    PROJECT_PERMISSIONS.DELETE_OWN,
    PROJECT_PERMISSIONS.UPDATE_OTHER,  

    DESIGN_PERMISSIONS.CREATE_UIUX,
    DESIGN_PERMISSIONS.VIEW_UIUX,

    BACKEND_PERMISSIONS.CREATE_BACKEND,
    BACKEND_PERMISSIONS.VIEW_BACKEND,
  ],
} ;